'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("P11.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property pal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pal_white_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pal_white_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pal3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pal3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Recoil]
        '''RecoilUp=0.55
        '''RecoilLeft=0.2
        '''RecoilRight=0.3
        '''FirstShot=1.3
        '''[Spread]
        '''SpreadMin=0.1
        '''SpreadInc=0.12
        '''[Burst]
        '''BurstsPerBullet=5
        '''Bursts=1000
        '''[Attach]
        '''RenderAttachText=0
        '''AttachRecoilV=0
        '''AttachRecoilH=0
        '''AttachSpreadMin=0
        '''AttachSpreadInc=0
        '''[Save]
        '''SavePath=C:\Users\Ripley\documents\visual studio 2010\Projects\Pl1\Pl1\bin\Debug
        '''FileName=&lt;&lt;TitleText&gt;&gt;_bf3_&lt;&lt;SubText&gt;&gt;
        '''[Render]
        '''ScaleRadius=1
        '''RenderBars=1
        '''[Title]
        '''RenderTitleText=1
        '''TitleText=AEK-17
        '''InfoText=Dmg: 25-17
        '''SubText=Stock
        '''[Gri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property plotic_silent() As String
            Get
                Return ResourceManager.GetString("plotic_silent", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sil_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sil_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sil_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sil_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sil_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sil_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sil_mask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sil_mask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
